services:
  mongo:
    image: mongo:7
    container_name: chunkd-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - chunkd-mongo-data:/data/db

volumes:
  chunkd-mongo-data:
