/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)

-- Incorrect sources -- 
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import { useGLTF } from "@react-three/drei";
import axeUrl from "../../assets/axe.glb";

// Uses gltf loader to load the model as a component.
//
// The two `false`s turn off Draco and Meshopt. drei enables both by default,
// and each brings a WebAssembly decoder: Draco's is fetched from Google's CDN
// on every visit, Meshopt's is compiled inline. Both need a
// Content-Security-Policy hole for 'wasm-unsafe-eval', and this model uses
// neither compression — it is 5 KB of plain glTF. Draco was saving 1.3 KB on it.
export default function Axe(props) {
  const { nodes, materials } = useGLTF(axeUrl, false, false);
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, -0.3]} scale={0.5}>
        <mesh
          geometry={nodes.Mesh_1001_1.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Mesh_1001_2.geometry}
          material={materials.material_3}
        />
      </group>
    </group>
  );
}
