/*
The held tool. The JSX was generated by https://github.com/pmndrs/gltfjsx
from the model in Paul Henschel's Minecraft sandbox
(https://codesandbox.io/s/vkgi6). The original Sketchfab listing is unknown;
an earlier comment credited Blender3D's "Minecraft Diamond Axe", which this
file is not.
*/

import { useGLTF } from "@react-three/drei";
import axeUrl from "../../assets/axe.glb";

// Uses gltf loader to load the model as a component.
//
// The two `false`s turn off Draco and Meshopt. drei enables both by default,
// and each brings a WebAssembly decoder: Draco's is fetched from Google's CDN
// on every visit, Meshopt's is compiled inline. Both need a
// Content-Security-Policy hole for 'wasm-unsafe-eval', and this model uses
// neither compression. It is 5 KB of plain glTF, and Draco was saving 1.3 KB on it.
export default function Axe(props) {
  const { nodes, materials } = useGLTF(axeUrl, false, false);
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, -0.3]} scale={0.5}>
        <mesh
          geometry={nodes.Mesh_1001_1.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Mesh_1001_2.geometry}
          material={materials.material_3}
        />
      </group>
    </group>
  );
}
