/*
The held tool. JSX generated by https://github.com/pmndrs/gltfjsx from the
model in Paul Henschel's Minecraft sandbox (https://codesandbox.io/s/vkgi6).
*/

import { useGLTF } from "@react-three/drei";
import axeUrl from "../../assets/axe.glb";

// The two `false`s turn off Draco and Meshopt, which drei enables by default.
// Each needs a WebAssembly decoder and a 'wasm-unsafe-eval' CSP hole, and this
// model uses neither compression.
export default function Axe(props) {
  const { nodes, materials } = useGLTF(axeUrl, false, false);
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, -0.3]} scale={0.5}>
        <mesh
          geometry={nodes.Mesh_1001_1.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Mesh_1001_2.geometry}
          material={materials.material_3}
        />
      </group>
    </group>
  );
}
